### PR TITLE
Updated pattern-library to 631dea2: Add content header for Digest

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies-patterns-php-update-pattern-library/633/ which resulted in this pull request.

### CODE REVIEW

**Comment by nlisgo** [comment]
@scottaubrey any chance you can take a look at this. I am not able to recreate the failures that we are experiencing in ci locally. All phpunit tests are passing for me.

**Comment by lsh-0** [comment]
`pattern-library--prod` has been building without errors for 20.04 and was upgraded Wednesday.

A quick look at the formula shows that it's using containers and has smoke tests, so any changes to PHP on the host machine shouldn't have affected whatever is running inside the container. 

The smoke tests were also successful, so whatever is running inside the container is happy.

Was the image upgraded in some way?

**Comment by scottaubrey** [comment]
@lsh-0 This is patterns-php, pattern-library is a different beast. This repo doesn't have a Dockerfile that I can see and the Jenkinsfile just runs `project_tests.sh` I think.

**Comment by lsh-0** [comment]
I didn't realise, in which case:
https://github.com/elifesciences/patterns-php/blob/50cc4135b35179448ab92226faf15628b789661c/Jenkinsfile#L1

means it's running without on an `elife-libraries` instance that *has* been upgraded and will have a different PHP version.

**Comment by scottaubrey** [comment]
Thanks, It's good to have the confirmation. /cc @nlisgo

**Pull request merged**
