### PR TITLE
ELPP-3349 Add PersonalisedCoverDownload

### PR DESCRIPTION
**Pull request by thewilkybarkid**
Implements https://github.com/elifesciences/pattern-library/pull/814.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
@garyttierney Could you try using this? It should work in the same way as our error pages (ie https://github.com/elifesciences/error-pages/blob/develop/resources/mustache/page.mustache - straight in the `<body>`).

**Comment by garyttierney** [comment]
@thewilkybarkid working for me, but no images rendering.  Maybe I have to do something to get that working?

Image: 
screenshot from 2018-02-07 15-52-52

Generated markup for the `picture` tag looks like so:
```
    <picture>
      <source srcset=""
              type="image/svg+xml">
      <img srcset=" 276w"
           src="" sizes="138px"
           alt="" class="download__icon">
    </picture>
```

**Comment by thewilkybarkid** [comment]
@garyttierney You need to add in the `assetsPath` and `assetRewrite` helpers (in the README). The former is the base path for assets, and the latter doesn't need to do anything to the value unless you add cache busting.

**Comment by garyttierney** [comment]
Yep that did the job.  I have a branch here that makes use of the pattern https://github.com/elifesciences/personalised-covers/tree/enhancement/new-pattern

**Pull request merged**
