### PR TITLE
Updated pattern-library to 1608b74: Support list being added to teaser content

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run http://ci--alfred.elifesciences.org/job/dependencies-patterns-php-update-pattern-library/234/ which resulted in this pull request.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
This shouldn't have been merged, there's no matching code change.

**Comment by nlisgo** [comment]
@thewilkybarkid apologies. I will work on the matching code changes. I think in this instance it shouldn't be too disruptive to leave the merge and submit a separate PR but if you think it would be better to revert than we can do that.

**Comment by thewilkybarkid** [comment]
The change is an addition so no need to revert in this case (more disruptive changes could break things), but we shouldn't have things out of sync. A follow-up PR with the code change is ok.

**Comment by nlisgo** [comment]
https://github.com/elifesciences/patterns-php/pull/447

**Pull request merged**
